/* ============================================
   CRATE ESCAPE — neon Sokoban.
   Push every crate onto a glowing pad. Levels
   are generated by REVERSE-PULLING crates off
   their pads with a fixed per-level seed: every
   pull is a legal push played backwards (player
   reachability included), so each level is
   solvable by construction and identical for
   every player — a fair shared ladder without
   shipping a level pack.
   Arrows/WASD push · Z undo · R restart.
   ============================================ */

const CrateEscapeGame = (() => {
  const WIDTH = 480, HEIGHT = 420;
  const MAX_LEVEL = 50;

  let canvas, ctx;
  let level, wall, goals, crates, player, gw, gh;
  let moves, pushes, history, solvedNow;
  let best, bestMoves;      // best: levels solved (HOF); bestMoves: {level: moves}
  let bound = false;
  const sfx = Utils.sfx;

  // Same mulberry32 the daily uses; the seed is a pure function of the
  // level number so everyone climbs the same ladder.
  function mulberry32(a) {
    return function () {
      a |= 0; a = a + 0x6D2B79F5 | 0;
      let t = Math.imul(a ^ a >>> 15, 1 | a);
      t = t + Math.imul(t ^ t >>> 7, 61 | t) ^ t;
      return ((t ^ t >>> 14) >>> 0) / 4294967296;
    };
  }
  const key = (x, y) => x + ',' + y;
  const DIRS = { up: [0, -1], down: [0, 1], left: [-1, 0], right: [1, 0] };

  // Player-reachable floor cells given walls + crates (plain flood fill).
  function flood(px, py, wallG, crateSet, w, h) {
    const seen = new Set([key(px, py)]);
    const q = [[px, py]];
    while (q.length) {
      const [x, y] = q.pop();
      for (const [dx, dy] of Object.values(DIRS)) {
        const nx = x + dx, ny = y + dy;
        if (nx < 0 || ny < 0 || nx >= w || ny >= h) continue;
        if (wallG[ny][nx] || crateSet.has(key(nx, ny)) || seen.has(key(nx, ny))) continue;
        seen.add(key(nx, ny));
        q.push([nx, ny]);
      }
    }
    return seen;
  }

  function tryGen(rng, w, h, nCrates, pulls) {
    const wallG = Array.from({ length: h }, (_, y) =>
      Array.from({ length: w }, (_, x) => x === 0 || y === 0 || x === w - 1 || y === h - 1));
    const nWalls = Math.floor((w - 2) * (h - 2) * 0.10);
    for (let i = 0; i < nWalls; i++) {
      wallG[1 + Math.floor(rng() * (h - 2))][1 + Math.floor(rng() * (w - 2))] = true;
    }
    const free = [];
    for (let y = 1; y < h - 1; y++) for (let x = 1; x < w - 1; x++) if (!wallG[y][x]) free.push([x, y]);
    if (free.length < nCrates + 4) return null;
    for (let i = free.length - 1; i > 0; i--) {           // seeded shuffle
      const j = Math.floor(rng() * (i + 1));
      [free[i], free[j]] = [free[j], free[i]];
    }
    const gs = free.slice(0, nCrates).map(c => [...c]);
    const cs = gs.map(c => [...c]);
    const crateSet = new Set(cs.map(c => key(...c)));
    let p = free.slice(nCrates).find(c => !crateSet.has(key(...c)));
    if (!p) return null;
    p = [...p];

    let moved = 0;
    for (let i = 0; i < pulls; i++) {
      const reach = flood(p[0], p[1], wallG, crateSet, w, h);
      const options = [];
      for (const c of cs) {
        for (const [dx, dy] of Object.values(DIRS)) {
          const side = [c[0] + dx, c[1] + dy], back = [c[0] + 2 * dx, c[1] + 2 * dy];
          const ok = pos => pos[0] > 0 && pos[1] > 0 && pos[0] < w - 1 && pos[1] < h - 1 &&
            !wallG[pos[1]][pos[0]] && !crateSet.has(key(...pos));
          if (ok(side) && ok(back) && reach.has(key(...side))) options.push({ c, side, back });
        }
      }
      if (!options.length) break;
      const o = options[Math.floor(rng() * options.length)];
      crateSet.delete(key(...o.c));
      o.c[0] = o.side[0]; o.c[1] = o.side[1];
      crateSet.add(key(...o.c));
      p = [...o.back];
      moved++;
    }
    if (moved < Math.max(3, pulls / 3)) return null;
    // The puzzle must actually be a puzzle: at least one crate off its pad.
    const goalSet = new Set(gs.map(g => key(...g)));
    if (cs.every(c => goalSet.has(key(...c)))) return null;
    return { wall: wallG, goals: gs, crates: cs.map(c => [...c]), player: p, gw: w, gh: h };
  }

  function genLevel(n) {
    const rng = mulberry32(0x9E3779B9 ^ Math.imul(n, 2654435761));
    const w = 7 + Math.min(3, Math.floor((n - 1) / 5));
    const h = 6 + Math.min(3, Math.floor((n - 1) / 7));
    const nCrates = Math.min(4, 1 + Math.floor((n - 1) / 4));
    const pulls = 6 + n * 2;
    for (let attempt = 0; attempt < 80; attempt++) {
      const res = tryGen(rng, w, h, nCrates, pulls);
      if (res) return res;
    }
    // Statistically unreachable; a hand-checked trivial room as last resort.
    return {
      wall: [
        [1, 1, 1, 1, 1], [1, 0, 0, 0, 1], [1, 0, 0, 0, 1], [1, 1, 1, 1, 1],
      ].map(r => r.map(Boolean)),
      goals: [[3, 1]], crates: [[2, 1]], player: [1, 1], gw: 5, gh: 4,
    };
  }

  function loadLevel(n, keepHistory) {
    level = Math.max(1, Math.min(MAX_LEVEL, n));
    const L = genLevel(level);
    wall = L.wall; goals = L.goals; gw = L.gw; gh = L.gh;
    crates = L.crates.map(c => [...c]);
    player = [...L.player];
    moves = 0; pushes = 0; solvedNow = false;
    if (!keepHistory) history = [];
    try { localStorage.setItem('crate-level', String(level)); } catch {}
    const ov = document.getElementById('crate-overlay');
    if (ov) ov.style.display = 'none';
    updateInfo();
    draw();
  }

  function snapshot() {
    return { p: [...player], c: crates.map(c => [...c]), m: moves, k: pushes };
  }

  function move(dir) {
    if (solvedNow) return;
    const [dx, dy] = DIRS[dir];
    const nx = player[0] + dx, ny = player[1] + dy;
    if (wall[ny][nx]) { sfx('move'); return; }
    const crate = crates.find(c => c[0] === nx && c[1] === ny);
    if (crate) {
      const cx = nx + dx, cy = ny + dy;
      if (wall[cy][cx] || crates.some(c => c[0] === cx && c[1] === cy)) { sfx('move'); return; }
      history.push(snapshot());
      crate[0] = cx; crate[1] = cy;
      pushes++;
      sfx('lock');
    } else {
      history.push(snapshot());
      sfx('move');
    }
    player = [nx, ny];
    moves++;
    if (history.length > 400) history.shift();
    checkSolved();
    updateInfo();
    draw();
  }

  function undo() {
    if (!history.length || solvedNow) return;
    const s = history.pop();
    player = [...s.p];
    crates = s.c.map(c => [...c]);
    moves = s.m; pushes = s.k;
    sfx('move');
    updateInfo();
    draw();
  }

  function checkSolved() {
    const goalSet = new Set(goals.map(g => key(...g)));
    if (!crates.every(c => goalSet.has(key(...c)))) return;
    solvedNow = true;
    sfx('clear');
    Effects.shakeCanvas(canvas, 5, 240);
    const prevBestMoves = bestMoves[level];
    if (!prevBestMoves || moves < prevBestMoves) {
      bestMoves[level] = moves;
      try { localStorage.setItem('crate-moves', JSON.stringify(bestMoves)); } catch {}
    }
    if (level > best) {
      best = level;
      try { localStorage.setItem('crate-best', String(best)); } catch {}
    }
    updateInfo();
    const lines = [`Solved in ${moves} moves (${pushes} pushes)`,
      `Level best: ${bestMoves[level]} moves &nbsp;·&nbsp; Ladder: ${best} solved`];
    Utils.showGameOver('crate-overlay', {
      lines,
      hint: level < MAX_LEVEL ? 'Press SPACE or tap for the next puzzle' : 'Ladder complete — press R to replay',
    });
  }

  function next() { if (level < MAX_LEVEL) loadLevel(level + 1); }

  function onKey(e) {
    const k = e.key.toLowerCase();
    if (solvedNow && (e.key === ' ' || e.key === 'Enter')) { e.preventDefault(); next(); return; }
    const map = { arrowup: 'up', w: 'up', arrowdown: 'down', s: 'down',
      arrowleft: 'left', a: 'left', arrowright: 'right', d: 'right' };
    if (map[k]) { e.preventDefault(); move(map[k]); }
    else if (k === 'z') { e.preventDefault(); undo(); }
    else if (k === 'r') { e.preventDefault(); loadLevel(level); }
  }

  function updateInfo() {
    const set = (id, v) => { const el = document.getElementById(id); if (el) el.textContent = v; };
    set('crate-level', level);
    set('crate-moves-hud', moves);
    set('crate-solved', best);
    const bm = bestMoves[level];
    set('crate-par', bm ? bm + ' moves' : '—');
  }

  function draw() {
    if (!ctx) return;
    ctx.fillStyle = '#0d1117';
    ctx.fillRect(0, 0, WIDTH, HEIGHT);
    const T = Math.min(Math.floor(WIDTH / gw), Math.floor(HEIGHT / gh));
    const ox = (WIDTH - gw * T) / 2, oy = (HEIGHT - gh * T) / 2;
    const goalSet = new Set(goals.map(g => key(...g)));

    for (let y = 0; y < gh; y++) {
      for (let x = 0; x < gw; x++) {
        const px = ox + x * T, py = oy + y * T;
        if (wall[y][x]) {
          ctx.fillStyle = '#21262d';
          ctx.fillRect(px + 1, py + 1, T - 2, T - 2);
          ctx.strokeStyle = 'rgba(255,255,255,0.06)';
          ctx.strokeRect(px + 3.5, py + 3.5, T - 7, T - 7);
        } else {
          ctx.fillStyle = 'rgba(255,255,255,0.02)';
          ctx.fillRect(px + 1, py + 1, T - 2, T - 2);
          if (goalSet.has(key(x, y))) {
            ctx.strokeStyle = '#3FB950';
            ctx.shadowColor = '#3FB950'; ctx.shadowBlur = 10;
            ctx.lineWidth = 2;
            ctx.strokeRect(px + T * 0.28, py + T * 0.28, T * 0.44, T * 0.44);
            ctx.shadowBlur = 0;
          }
        }
      }
    }
    for (const c of crates) {
      const onGoal = goalSet.has(key(...c));
      const px = ox + c[0] * T, py = oy + c[1] * T;
      ctx.fillStyle = onGoal ? '#3FB950' : '#F0883E';
      ctx.shadowColor = ctx.fillStyle; ctx.shadowBlur = onGoal ? 14 : 8;
      ctx.fillRect(px + T * 0.14, py + T * 0.14, T * 0.72, T * 0.72);
      ctx.shadowBlur = 0;
      ctx.strokeStyle = 'rgba(13,17,23,0.6)'; ctx.lineWidth = 2;
      ctx.strokeRect(px + T * 0.26, py + T * 0.26, T * 0.48, T * 0.48);
    }
    {
      const px = ox + player[0] * T, py = oy + player[1] * T;
      ctx.fillStyle = '#22d3ee';
      ctx.shadowColor = '#22d3ee'; ctx.shadowBlur = 14;
      ctx.beginPath();
      ctx.arc(px + T / 2, py + T / 2, T * 0.30, 0, Math.PI * 2);
      ctx.fill();
      ctx.shadowBlur = 0;
    }
  }

  function init() {
    canvas = document.getElementById('crate-canvas');
    if (!canvas) return;
    const dpr = Math.max(1, window.devicePixelRatio || 1);
    canvas.width = WIDTH * dpr; canvas.height = HEIGHT * dpr;
    canvas.style.width = '100%';
    canvas.style.maxWidth = WIDTH + 'px';
    ctx = canvas.getContext('2d');
    ctx.setTransform(dpr, 0, 0, dpr, 0, 0);

    best = Utils.highScore.load('crate-best');
    try { bestMoves = JSON.parse(localStorage.getItem('crate-moves') || '{}') || {}; } catch { bestMoves = {}; }
    let startAt = best + 1;
    try { startAt = parseInt(localStorage.getItem('crate-level') || '0', 10) || best + 1; } catch {}

    if (!bound) {
      bound = true;
      document.addEventListener('keydown', Utils.whenViewActive('view-crateescape', onKey));
      const ov = document.getElementById('crate-overlay');
      if (ov) ov.addEventListener('click', () => { if (solvedNow) next(); });
      // Touch: swipe pushes.
      let sx = 0, sy = 0;
      canvas.addEventListener('touchstart', e => { sx = e.touches[0].clientX; sy = e.touches[0].clientY; }, { passive: true });
      canvas.addEventListener('touchend', e => {
        const dx = e.changedTouches[0].clientX - sx, dy = e.changedTouches[0].clientY - sy;
        if (Math.abs(dx) < 24 && Math.abs(dy) < 24) return;
        if (Math.abs(dx) > Math.abs(dy)) move(dx > 0 ? 'right' : 'left');
        else move(dy > 0 ? 'down' : 'up');
      }, { passive: true });
    }
    loadLevel(startAt);
  }

  function start() { loadLevel(level || 1); }

  function prevLevel() { if (level > 1) loadLevel(level - 1); }
  function nextLevel() { if (level <= best && level < MAX_LEVEL) loadLevel(level + 1); }
  function restart() { loadLevel(level); }
  function undoBtn() { undo(); }

  function destroy() {
    const ov = document.getElementById('crate-overlay');
    if (ov) ov.style.display = 'none';
    // The other arcade games rewind to their idle start screen here, because
    // SPACE always begins a fresh run there. This is a ladder, not a run: the
    // only thing that advances it is the overlay's "press SPACE for the next
    // puzzle", so clearing solvedNow and hiding that prompt left the player
    // coming back to a finished board with nothing left to press — SPACE
    // inert, every crate already on its pad, the game looking over. Advance
    // the ladder exactly as that SPACE would; the last rung has no next one,
    // so re-deal it, which is the replay its own hint offers.
    if (solvedNow) { loadLevel(level < MAX_LEVEL ? level + 1 : level); return; }
    draw();
  }

  return { init, start, destroy, prevLevel, nextLevel, restart, undoBtn };
})();
